# Generated by Django 2.0.8 on 2018-11-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0048_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='apply_notification',
            field=models.BooleanField(default=False, help_text='Whether this organization auto_accepted the migration of staging to production'),
        ),
        migrations.AlterField(
            model_name='org',
            name='brand',
            field=models.CharField(default='rapidpro.datos.gob.mx', help_text='The brand used in emails', max_length=128, verbose_name='Brand'),
        ),
    ]
