# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-16 17:06
from __future__ import unicode_literals

from django.db import migrations

SQL = """
CREATE INDEX IF NOT EXISTS msgs_broadcast_sending_idx ON msgs_broadcast(org_id, created_on) WHERE status = 'Q';


CREATE INDEX IF NOT EXISTS msgs_msg_org_id_created_on_id_idx on msgs_msg(org_id, created_on, id);

"""


class Migration(migrations.Migration):

    dependencies = [("msgs", "0126_initial")]

    operations = [migrations.RunSQL(SQL)]
